config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :conversations do
    resources :messages
  end

  resources :seekers do
    collection do
      get :home
    end
  end
  
  resources :employers do
    collection do
      get :home
    end
  end

  resources :resumes
  resources :posts

end

app/models/seeker.rb
class Seeker < ActiveRecord::Base
	#attr_accessible :current_user.id
	belongs_to :user

	validates :firstname, :lastname, :contact, :current_location, :dob, :permanent_address, :nationality, :gender, presence: true
	validates :photo, presence: true, on: :create
	mount_uploader :photo, PictureUploader
end

app/controllers/seekers_controller.rb
class SeekersController < ApplicationController
	layout "seeker_home"
	def new
		@seeker=Seeker.new
	end

	def index
		
	end

	def create
		@seeker = current_user.build_seeker(detail_params)
		if @seeker.save
			redirect_to @seeker
		else
			render :action => 'new'
		end
	end

	def edit
		@seeker= current_user.seeker(params[:id])
	end

	def update
		@seeker= current_user.seeker(params[:id])
		if @seeker.update(detail_params)
			redirect_to @seeker
		else
			render 'edit'
		end
	end

	def show
		@seeker= current_user.seeker(params[:id])
		@email = @seeker.user.email
	end
	def home
		@seeker= current_user.seeker(params[:id])
    end
	private
    def detail_params
      params.require(:seeker).permit(:photo, :firstname, :lastname, :contact, :current_location, :dob, :permanent_address, :nationality, :gender)
    end
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/views/seekers/edit.html.erb
<% if @seeker.errors.any? %>
  <div id="error_explanation table-responsive">
    <h2><%= pluralize(@seeker.errors.count, "error") %> prohibited from being saved:</h2>
    <ul>
      <% @seeker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for(@seeker) do |f| %>
  <table class="table table-hover">
    <tr><td>Firstname</td><td><%= f.text_field :firstname %></td></tr>
    <tr><td>Lastname</td><td><%= f.text_field :lastname %></td></tr>
    <tr><td>Gender</td><td><%= f.radio_button 'gender', "male" %> MALE
                  <%= f.radio_button 'gender', "female" %> FEMALE</td></tr>
    <tr><td>Contact no.</td><td><%= f.text_field :contact %></td></tr>
    <tr><td>Current Location</td><td><%= f.text_field :current_location %></td></tr>
    <tr><td>Date Of Birth</td><td><%= f.date_select(:dob, :start_year=>1900, :end_year =>2030) %></td></tr>
    <tr><td>Nationality</td><td><%= f.select :nationality, options_for_select([["INDIA", "india"], ["USA", "usa"]]) %></td></tr>
    <tr><td>Permanent Address</td><td><%= f.text_area :permanent_address %></td></tr>
    <tr><td>Photo</td><td><%= image_tag(@current_user.seeker.photo_url, :size => "100x120") if @current_user.seeker. photo.present? %></td></tr>
    <tr><td>Change Photo </td><td><%= f.file_field :photo %></td></tr>
  </table>
  <br/>
  <div><%= f.submit "Done"%></div>
<% end %>

app/views/seekers/home.html.erb
<%= @current_user.email %>
<br/>
<%= image_tag(@current_user.seeker.photo_url, :size => "100x120") if @current_user.seeker.photo.present? %>
<br/>
<h3> Home Job _Seeker </h3>

<div id='calendar'>
</div>

<script>
  $(document).ready(function () {
    $('#calendar').fullCalendar();
  })
</script>

app/views/seekers/index.html.erb
<div style="margin-top:0px;">
  <table>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index +=1 %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
          "data-sid" => current_user.id, "data-rip" => user.id %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/seekers/new.html.erb
<h1>Add Some More Detail</h1>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>

 <% if @seeker.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@seeker.errors.count, "error") %> prohibited
      from being saved:</h2>
    <ul>
    <% @seeker.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for(@seeker, :html => {:multipart => true}, url: seekers_path) do |f| %>
  <table>
    <tr><td>Firstname</td><td><%= f.text_field :firstname %></td></tr>

    <tr><td>Lastname</td><td><%= f.text_field :lastname %></td></tr>

    <tr><td>Gender</td><td><%= f.radio_button 'gender', "male" %> MALE
                   <%= f.radio_button 'gender', "female" %> FEMALE</td></tr>

    <tr><td>Contact no.</td><td><%= f.text_field :contact %></td></tr>

    <tr><td>Current Location</td><td><%= f.text_field :current_location %></td></tr>

    <tr><td>Date Of Birth</td><td><%= f.date_select(:dob, :start_year=>1900, :end_year =>2030) %></td></tr>

    <tr><td>Nationality</td><td><%= f.select :nationality, options_for_select([["INDIA", "india"], ["USA", "usa"]]) %></td></tr>

    <tr><td>Permanent Address</td><td><%= f.text_area :permanent_address %></td></tr>
    <tr><td>Profile Photo</td><td><%= f.file_field :photo %></td></tr>

  </table>
  <div><%= f.submit "Done"%></div>

<% end %>

app/views/seekers/show.html.erb
<p>
  <strong>Email:</strong> <%= @email %>
</p>
<p>
  <strong>Firstname:</strong> <%= @current_user.seeker.firstname %>
</p>
<p>
  <strong>Lastname:</strong> <%= @current_user.seeker.lastname %>
</p>
<p>
  <strong>Contact no. :</strong> <%= @current_user.seeker.contact %>
</p>

<p>
  <strong>Gender :</strong> <%= @current_user.seeker.gender %>
</p>
<p>
  <strong>Current Location:</strong> <%= @current_user.seeker.current_location %>
</p>

<p>
  <strong>DOB :</strong> <%= @current_user.seeker.dob %>
</p>
<p>
  <strong>Permanent Address:</strong>  <%= @current_user.seeker.permanent_address %>
</p>

<p>
  <strong>Nationality :</strong>  <%= @current_user.seeker.nationality %>
</p>
<p>
<%= image_tag(@current_user.seeker.photo_url, :size => "100x120") if @current_user.seeker. photo.present? %>
</p>
<%= link_to 'Edit Detail', edit_seeker_path %>