config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :conversations do
    resources :messages
  end

  resources :seekers do
    collection do
      get :home
    end
  end
  
  resources :employers do
    collection do
      get :home
    end
  end

  resources :resumes
  resources :posts

end

app/models/employer.rb
class Employer < ActiveRecord::Base
	belongs_to :user
	validates :company_name, :company_type, :contact, :address, :doo, :country, :state, :city, :pincode, :total_employee, presence: true
	validates :icon, presence: true, on: :create
	mount_uploader :icon, PictureUploader
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
	layout "employer_home"
	def index
	end

	def new
		@employer=Employer.new
	end

	def create
	  @employer = current_user.build_employer(values_employ)
		if @employer.save
			redirect_to @employer
		else
			render 'new'
		end
	end

	def edit
		@employer = current_user.employer(params[:id])
	end

	def update
		@employer = current_user.employer(params[:id])
		if @employer.update(values_employ)
			redirect_to @employer
		else
			render 'edit'
		end
	end

	def show
		@employer=current_user.employer(params[:id])
	end

	def home
		@employer=current_user.employer(params[:id])
	end

	private

	def values_employ
		params.require(:employer).permit(:icon, :company_name, :company_type, :contact, :address, :doo, :country, :state, :city, :pincode, :total_employee)
	end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/edit.html.erb
<% if @employer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@employer.errors.count, "error") %> prohibited
      from being saved:</h2>
    <ul>
    <% @employer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<%= form_for(@employer) do |f| %>
  <table>
    <tr><td>Company Name</td><td><%= f.text_field :company_name %></td></tr>

    <tr><td>Company Type</td><td><%= f.radio_button 'company_type', "Company" %> COMPANY
                                 <%= f.radio_button 'company_type', "consultancy" %> CONSULTANCY</td></tr>

    <tr><td>Date Of Opening</td><td><%= f.date_select(:doo, :start_year=>1900, :end_year =>2030) %></td></tr>

    <tr><td>Contact no.</td><td><%= f.text_field :contact %></td></tr>

    <tr><td>Address</td><td><%= f.text_field :address %></td></tr>

    <tr><td>Country</td><td><%= f.select :country, options_for_select([["INDIA", "india"], ["USA", "usa"]]) %></td></tr>

    <tr><td>State</td><td><%= f.text_field :state %></td></tr>

    <tr><td>City</td><td><%= f.text_field :city %></td></tr>

    <tr><td>Pincode</td><td><%= f.text_field :pincode %></td></tr>

    <tr><td>Total Employee</td><td><%= f.text_field :total_employee %></td></tr>
    <tr><td>Old Icon</td><td><%= image_tag(@current_user.employer.icon_url,  :size => "160x80") if @current_user.employer.icon.present? %></td></tr>
    <tr><td>Replace Icon</td><td><%= f.file_field :icon %></td></tr>
  </table>
  <div><%= f.submit "Done"%></div>

<% end %>

app/views/employers/home.html.erb
<%= @current_user.email %>
<br/>
<%= image_tag(@current_user.employer.icon_url, :size => "160x80") if @current_user.employer.icon.present? %>

<h1> HOME EMPLOYER </h1>
<br/>
<%= link_to 'Show deatil', employer_path(current_user), :method => :get %>
&nbsp;&nbsp;<%= link_to 'Ad-Post', new_post_path %>

app/views/employers/new.html.erb
<h1>Some more about Your Company</h1>
<% if @employer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@employer.errors.count, "error") %> prohibited
      from being saved:</h2>
    <ul>
    <% @employer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<%= form_for(@employer,:html => {:multipart => true}, url: employers_path) do |f| %>
  <table>
    <tr><td>Company Name</td><td><%= f.text_field :company_name %></td></tr>

    <tr><td>Company Type</td><td><%= f.radio_button 'company_type', "Company" %> COMPANY
                                 <%= f.radio_button 'company_type', "consultancy" %> CONSULTANCY</td></tr>

    <tr><td>Date Of Opening</td><td><%= f.date_select(:doo, :start_year=>1900, :end_year =>2030) %></td></tr>

    <tr><td>Contact no.</td><td><%= f.text_field :contact %></td></tr>

    <tr><td>Address</td><td><%= f.text_field :address %></td></tr>

    <tr><td>Country</td><td><%= f.select :country, options_for_select([["INDIA", "india"], ["USA", "usa"]]) %></td></tr>

    <tr><td>State</td><td><%= f.text_field :state %></td></tr>

    <tr><td>City</td><td><%= f.text_field :city %></td></tr>

    <tr><td>Pincode</td><td><%= f.text_field :pincode %></td></tr>

    <tr><td>Total Employee</td><td><%= f.text_field :total_employee %></td></tr>
    <tr><td>Company Icon</td><td><%= f.file_field :icon %></td></tr>

  </table>
  <div><%= f.submit "Done"%></div>

<% end %>

app/views/employers/show.html.erb
<h1> Employer Detail </h1>

<p> <strong>Company Name:</strong> <%= @current_user.employer.company_name %> </p>
<p> <strong>Company Type:</strong> <%= @current_user.employer.company_type %> </p>
<p> <strong>Contact no. :</strong> <%= @current_user.employer.contact %> </p>
<p> <strong>Address:</strong> <%= @current_user.employer.address %> </p>
<p> <strong>Date Of Opening:</strong> <%= @current_user.employer.doo %> </p>
<p> <strong>Country :</strong> <%= @current_user.employer.country %> </p>
<p> <strong>State:</strong>  <%= @current_user.employer.state %> </p>
<p> <strong>City :</strong>  <%= @current_user.employer.city %> </p>
<p> <strong>Pincode :</strong>  <%= @current_user.employer.pincode %> </p>
<p> <strong>Total Employee :</strong>  <%= @current_user.employer.total_employee %> </p>
<p>
<%= image_tag(@current_user.employer.icon_url, :size => "160x80") if @current_user.employer.icon.present? %>
</p>

<%= link_to 'Edit Detail', edit_employer_path %>