config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :conversations do
    resources :messages
  end

  resources :seekers do
    collection do
      get :home
    end
  end
  
  resources :employers do
    collection do
      get :home
    end
  end

  resources :resumes
  resources :posts

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :user
	mount_uploader :attach_resume, PictureUploader

	validates :resume_heading, :functional_area, :current_company, :position, :key_skills, :total_experience, :expected_salary, :highest_qualification, :attach_resume, presence: true, on: :create
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  layout "seeker_home"
  def new
    @resume=Resume.new
  end

  def index
     @resumes = current_user.resumes
  end

  def create
    @resume = current_user.resumes.new(detail_params)
    if @resume.save
      redirect_to :back
    else
      render 'new'
    end
  end

  def edit
    @resume = current_user.resumes.find(params[:id])
  end

  def update
    @resume = current_user.resumes.find(params[:id])
    if @resume.update(update_params)
      redirect_to @resume
    else
      render 'edit'
    end
  end

  def show
    @resume = current_user.resumes.find(params[:id])
  end

  def destroy
    @resume = current_user.resumes.find(params[:id])
    @resume.destroy
    redirect_to resumes_path

  end

  private
  def detail_params
    params.require(:resume).permit(:resume_heading, :functional_area, :current_company, :position, :key_skills, :total_experience, :attach_resume, :expected_salary, :highest_qualification)
  end

  private
  def update_params
    params.require(:resume).permit(:resume_heading, :functional_area, :current_company, :position, :key_skills, :total_experience, :attach_resume, :expected_salary, :highest_qualification, :active)
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for @resume, :html => { :class => "form-horizontal resume" } do |f| %>

    <% if @resume.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :resume_heading, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :resume_heading, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:resume_heading]) %>
  </div>
  <div class="control-group">
    <%= f.label :functional_area, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :functional_area, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:functional_area]) %>
  </div>
  <div class="control-group">
    <%= f.label :current_company, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_company, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:current_company]) %>
  </div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:position]) %>
  </div>
  <div class="control-group">
    <%= f.label :key_skills, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :key_skills, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:key_skills]) %>
  </div>
  <div class="control-group">
    <%= f.label :total_experience, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total_experience, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:total_experience]) %>
  </div>
  <div class="control-group">
    <%= f.label :attach_resume, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :attach_resume%>
    </div>
    <%= error_span(@resume[:attach_resume]) %>
  </div>
  <div class="control-group">
    <%= f.label :expected_salary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :expected_salary, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:expected_salary]) %>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :active, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:active]) %>
  </div>
  <div class="control-group">
    <%= f.label :highest_qualification, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :highest_qualification, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:highest_qualification]) %>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%= error_span(@resume[:user_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            resumes_path, :class => 'btn btn-default' %>

<% end %>

app/views/resumes/edit.html.erb
<%- model_class = Resume -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/resumes/index.html.erb
<script>
  $(function() {
    $( "#dialog" ).dialog({
      autoOpen: false,
      show: {
        effect: "blind",
        duration: 1000
      },
      hide: {
        effect: "explode",
        duration: 1000
      }
    });
    $( "#opener" ).click(function() {
      $( "#dialog" ).dialog( "open" );
    });
  });

</script>

  <div id="dialog" title="Basic dialog">
    <%= form_for :resume, :url => {:action => "create", :controller => "resumes" } do |f| %>
      <label for="resume_heading">Resume Heading</label>
      <%= f.text_field :resume_heading, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="functional_area">Functional Area</label>
      <%= f.text_field :functional_area, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="current_company">Current Company</label>
      <%= f.text_field :current_company, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="position">Position</label>
      <%= f.text_field :position, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="key_skills">Key Skills</label>
      <%= f.text_area :key_skills, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="total_experience">Total Experience</label>
      <%= f.text_field :total_experience, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="expected_salary">Expected Salary</label>
      <%= f.text_field :expected_salary, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="highest_qualification">Higest Qualification</label>
      <%= f.text_field :highest_qualification, :class=>"text ui-widget-content ui-corner-all" %>
      <label for="attach_resume">Attach Resume</label>
      <%= f.file_field :attach_resume, :class=>"text ui-widget-content ui-corner-all" %>
      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <%= f.submit "Create" %>
    <% end %>
  </div>

  <div id="users-contain" class="ui-widget table-responsive">
    <h1>List of all Resumes:</h1>
    <table id="users" class="ui-widget ui-widget-content table table-hover">
      <thead>
        <tr class="ui-widget-header ">
          <th>Resume Heading</th>
          <th>Functional Area</th>
          <th>Position</th>
          <th>Key Skills</th>
          <th>Total Experience</th>
          <th>Expected Salary</th>
          <th>Active Status</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
      <% @resumes.each do |resume| %>
        <tr>
          <td><%= resume.resume_heading %></td>
          <td><%= resume.functional_area %></td>
          <td><%= resume.position %></td>
          <td><%= resume.key_skills %></td>
          <td><%= resume.total_experience %></td>
          <td><%= resume.expected_salary %></td>
          <td><%= resume.active %></td>
          <td><%= link_to "", edit_resume_path(resume), class: "btn btn-info glyphicon glyphicon-edit" %></td>
          <td><%= link_to "", resume, :method =>'delete', class: "btn btn-danger glyphicon glyphicon-trash" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  <button id="opener" class = "btn btn-success">Create New Resume</button>

app/views/resumes/new.html.erb
<%- model_class = Resume -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/resumes/show.html.erb
<%- model_class = Resume -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:resume_heading) %>:</strong></dt>
  <dd><%= @resume.resume_heading %></dd>
  <dt><strong><%= model_class.human_attribute_name(:functional_area) %>:</strong></dt>
  <dd><%= @resume.functional_area %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_company) %>:</strong></dt>
  <dd><%= @resume.current_company %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @resume.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key_skills) %>:</strong></dt>
  <dd><%= @resume.key_skills %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_experience) %>:</strong></dt>
  <dd><%= @resume.total_experience %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attach_resume) %>:</strong></dt>
  <dd><%= image_tag(@resume.attach_resume_url, :size => "100x120") if @resume.attach_resume_url.present? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expected_salary) %>:</strong></dt>
  <dd><%= @resume.expected_salary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @resume.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:highest_qualification) %>:</strong></dt>
  <dd><%= @resume.highest_qualification %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @resume.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              resumes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_resume_path(@resume), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              resume_path(@resume),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>